server:
  port: 9999
  servlet:
    context-path: /api
spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
--- # 개발
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/sera;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
--- # 배포
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://seradb.c8joeykpqvdy.ap-northeast-2.rds.amazonaws.com:3306/seraDB?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: ssafyB202SERA
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate