server:
  port: 9999
  servlet:
    context-path: /api
spring:
  profiles:
    active: prod
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
--- # 개발
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/sera;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
--- # 배포
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://sera.czh6yt8bx4v6.ap-northeast-2.rds.amazonaws.com:3306/seraDB?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: ssafyB202SERA
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
--- # AWS S3
cloud:
  aws:
    credentials:
      accessKey: AKIAV4C36BHFEEJUSSMI
      secretKey: 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
    s3:
      bucket: myserabucket
    region:
      static: ap-northeast-2
    stack:
      auto: false